extraction:
  cpp:
    configure:
      command:
        - cd Project/GNU/Library
        - ./autogen.sh
        - ./configure
    index:
      build_command:
        - cd Project/GNU/Library
        - make
